"""Initial

Revision ID: 19f044c49c0a
Revises: 6054e2da6835
Create Date: 2023-07-05 13:06:12.408406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f044c49c0a'
down_revision = '6054e2da6835'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
