"""Initial

Revision ID: 9cb78f24a059
Revises: a6099e4c2815
Create Date: 2023-07-02 15:58:48.843708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb78f24a059'
down_revision = 'a6099e4c2815'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
